# Generated by Django 5.2.6 on 2025-09-16 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories_per_100g', models.FloatField(default=0)),
                ('proteins_per_100g', models.FloatField(default=0)),
                ('carbs_per_100g', models.FloatField(default=0)),
                ('fats_per_100g', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='meal',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='carbs',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='date',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='fats',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='image',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='proteins',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='user',
        ),
        migrations.AddField(
            model_name='meal',
            name='total_calories',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meal',
            name='total_carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meal',
            name='total_fats',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meal',
            name='total_proteins',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serving_size', models.CharField(choices=[('small', 'Small'), ('middle', 'Middle'), ('large', 'Large')], default='middle')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.fooditem')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.meal')),
            ],
        ),
    ]
