# Generated by Django 5.2.6 on 2025-09-22 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='calories',
            field=models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(600)]),
        ),
    ]
