# Generated by Django 5.2.6 on 2025-09-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_weightentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='goal',
            field=models.CharField(choices=[('lose_weight', 'Lose weight'), ('maintain_weight', 'Maintain weight'), ('gain_weight', 'Gain weight')], default='maintain_weight'),
        ),
    ]
