# Generated by Django 5.2.6 on 2025-09-25 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_meal_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectedPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/corrected_predictions')),
                ('model_prediction', models.CharField(max_length=200)),
                ('correct_prediction', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateTimeField(default=datetime.date(2025, 9, 25)),
        ),
    ]
