# Generated by Django 5.2.6 on 2025-09-25 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_correctedprediction_alter_meal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.image'),
        ),
    ]
