# Generated by Django 5.2.6 on 2025-09-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_meal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
