# Generated by Django 5.2.6 on 2025-09-22 18:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_meal_saved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=20)),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('diverse', 'diverse')])),
                ('height', models.IntegerField(default=180, validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(240)])),
                ('weight', models.FloatField(default=75, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(200)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
