# Generated by Django 5.2.6 on 2025-09-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_profile_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
