# Generated by Django 5.2.6 on 2025-09-26 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_meal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateTimeField(default=datetime.date(2025, 9, 26)),
        ),
    ]
