# Generated by Django 5.2.6 on 2025-09-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_meal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activity',
            field=models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], default='moderate'),
        ),
        migrations.AddField(
            model_name='profile',
            name='num_workouts',
            field=models.CharField(choices=[('0-1', '0-1 workouts per week'), ('2-3', '2-3 workouts per week'), ('4+', '4+ workouts per week')], default='0-1'),
        ),
        migrations.AddField(
            model_name='profile',
            name='workouts_per_week',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
