# Generated by Django 5.2.6 on 2025-09-26 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_profile_activity_profile_num_workouts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='workouts_per_week',
        ),
        migrations.AddField(
            model_name='profile',
            name='carbs',
            field=models.IntegerField(default=150, validators=[django.core.validators.MinValueValidator(40)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='fats',
            field=models.IntegerField(default=150, validators=[django.core.validators.MinValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='proteins',
            field=models.IntegerField(default=95, validators=[django.core.validators.MinValueValidator(30)]),
        ),
    ]
